### ISSUE TITLE
How luminosities are handled

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#258]
I have been trying to construct lum_tot to verify that we are actually getting the right answers for our ionization balance.  What I find however  looks like a mess in the code, where total_emission does not include all of the cooling processes, etc.  I'd like comments from @Higginbottom and @jhmatthews before I do much because I want to make sure that we are consistent with one another.  

When I say things are a mess, what I mean are lines in things like zero_emit, where we seem to compute the heating balance

```
 difference = xxxplasma->heat_tot - xxxplasma->lum_adiabatic - xxxplasma->lum_dr - xxxplasma->lum_di - xxxplasma->lum_comp - total_emission (&wmain[xxxplasma->nwind], 0., VERY_BIG);
```
Why is it that total emission does not include all of the processes, especially lum_comp.  Do we need a new variable cool_tot to capture the totol cooling.  Is lum_rad supposed to capture the total_emission?

The confusion extends to python.h where we have variables like 

```
 double lum_dr;                /* 1109 NSH The dielectronic recombination luminosity of the cell */
```
Is this a luminosity or a cooling term.  

And another question for each you.  Is zero_emit always called when we are trying to balance heating and cooling, and so is this the place we should actually be calculating all of these things and storing them in the plasma array so we can see the state at the end of an ionization cycle?

More generally, can you all suggest how we might make all of this clearer in the code, as misunderstandings here will certainly affect how easily if will be to sort out what is going on in the optically thick case (where different processes make relatively more contributions than we are typically used to).

**Comment by jhmatthews** [comment]
I think the main point here is that lum_dr, lum_comp etc are not used to actually produce wind photons, so are just cooling terms in this context. I believe lum_comp is essentially taken care of in the actual scattering event, by adjusting the weight and frequency of photons that "upscatter" in the plasma. I am not sure what we currently do with DR as I thought we now produced DR photons via Milne+Auger cross-sections. DI is a way for thermal energy to be converted to ionization energy and so doesn't create photons directly. I agree the whole thing is a bit of a mess, at least semantically if nothing else.

There is definitely an issue with reporting zero_emit when you are in a situationn where the temperature is trying to drop or fall dramatically. In that case the final call to zero_emit is the lower bound and can repopulate e.g. lum_dr with a luminosity that is inconsistent with the temperature python adopts for the next cycle. This is a reporting issue only, I believe. Hope I've understood the question right. I discussed it briefly here w.r.t DR: https://sites.google.com/site/agnwinds/current-work-in-progress/radiation-hydro/apr-2017---optically-thick-runs/cool-thin-shell-tests

Nick might be able to provide a bit more info than me on the former issue.

**Comment by kslong** [comment]
What I think would help here for the moment is to carefully comment all of the variables related to this in python.h, but please do this on the low_temp branch because that is where I am working.  

In terms of reporting, we should try to be clear on what it is that is contained in the windsave files and know that it makes sense.

For example, I believe that when we report on heating for a cycle, we are reporting on the heating during a cycle.  Should we therefore be calculating luminosities for the conditions that are derived from the t_e, etc. during the cycle, and before the heating and cooling are balanced.

**Comment by kslong** [comment]
I have now implemented lum_tot so that it is calculated in zero_emit, which may or may not be the right place to do this.

**Comment by Higginbottom** [comment]
I thought DR should indeed be a part of the total_emission calculation. This may well be a bug if it is being subtracted twice. Since DR is very important in the X-ray dominated calculations, this could be serious. I've divested myself of my laptop for the afternoon since we are off to dinner straight after the conference today, but I'll look into it tomorrow. 
Lum_DR should be a cooling term and also a luminosity, they are the same. Calling it lum was just following the format of the code when I started work
James is correct about lum_comp, the cooling comes from changing the frequencies of photons in flight
Finally, I think total_emission is called again before outputting the wind, or generating the photons sp I think the luminosities are correct for the current best guess of t_e. 
But I'll check all this when I get my laptop in front of me.

**Comment by Higginbottom** [comment]
Ok,
So I've reminded myself about a few things. I still don't quite know how to make photons from dielectronic recombination, so rather unsatisfactorily DR is not included in total emission. It is therefore not counted twice, but photons aren't made to match the (sometimes dominant) cooling. I guess this should be fixed. We could make photons just like we do for outer shell recombination, which would not be the right spectrum, but would maintain energy balance. I do have fluorescent yields in the code. We could make these photons, and then top up if necessary with Milne relation photons. 
We should talk about this!!

**Comment by Higginbottom** [comment]
The fluorescent yields are of course for auger ionisation, but dielectronic recombination. Probably not suitable.
