### ISSUE TITLE
shell wind is not working

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#412]
@Higginbottom  shell wind is currently failing which explains why Nick's attempt to fix #397 is also failing as the example he used to test this included a shell wind.  

For reasons that are currently unclear, the routine is has thinks the first cell is in the wind, even though it should not be.  

Although this is not the cause fo the problem above, the shell wind also lacks a number of checks and some of the checks should be carried out earlier.  For example, there is no check that rmax is greater than rmin for the shell wind model.  Furthermore, although the shell wind is intended to be run only in spherical coordinates the check is made after all of the inputs have been read in, and the shell wind is not initialized to spherical coordinates.

**Comment by kslong** [comment]
An issue that is associated with all of this, or at least is associated with #397  is that geo.rmin and 
The reason that the routine  thinks cell zero is in the wind, is that for whatever reason, the first cell is not in the positive x,z part of space.

Some other associated issues with all of this

geo.rmax which are supposed to be the radii inside of which and outside of which one assumes the photon is no longer in any wind, are assigned rather haphazardly.  We have analogous variables in domains (and these are used more often), but ...  one would think one should look at the domain values and then construct rmin and rmax from that.

This is most like a vestige of not really cleaning up all of the domain information.  On the other hand, it is not clear that this relates to this problem (which is occurring when we only have one domain)

Note that geo.rmin is only used in setup_dfudge to setup dfudge, while geo.rmax is used to determine when a photon is coursing through the universe.

**Comment by Higginbottom** [comment]
I'm a little confused.
Shell wind seems to work in a case like this:

[input.pf.txt](https://github.com/agnwinds/python/files/2266568/input.pf.txt)

I'm happy to help fix up shell wind, since it was my making but I need a .pf file that shows it failing in a sample case. Or is it only a multiple domain related problem?

I just merged/pulled the latest version and my model that started this still crashes. Thats this model for anyone else following along!

[py_hydro_dom.pf.txt](https://github.com/agnwinds/python/files/2266584/py_hydro_dom.pf.txt)

**Comment by kslong** [comment]
I have fixed that problem.  The problem had to do with the specific way cell 0 was setup which depended both on the rmin and rmax.  If rmax was sufficiently larger than rmin, then the radius for cell 0 ended up as negative, and this caused a number of downstream problem.  I am currently cleaning up some of the other problems I uncovered when I looked at this, namely how unsystematically geo.rmax and geo.rmin were assigned.  I am actually going to remove geo.rmin as it is only actually used in setting up the global DFUDGE.

**Comment by kslong** [comment]
@Higginbottom   I have fixed both the original (shell_wind was failing for certain choices of rmin and rmax) and some of the subsidiary issues (geo.rmin and geo.rmax were being assigned in inconsistent ways).  

To reemphasize, the problem I ran into was a situation where rmax was say 10x larger than rmin.  In the original code this there was line of code that set r for the 0 cell to something like

r = rmin - (rmax-rmin) = 2 * rmin - rmax --> r is less than 0

I replaced this with

r = 0.95 * rmin  

which has the distinct advantage that it is always positive.  For consistency, I also did something similar for cell 4.  

The new solution should also work for a thin shell (where the original solution also worked)

For the latter, 

- I've  eliminated geo.rmin altogether as it was not used in the code really, except to set up the global DFUDGE, and 
- for geo.rmax, I now calculate from zdom[ndom].rmax outside of the individual wind domain specifications

**Comment by Higginbottom** [comment]
Ah OK.
Just pulled in your new changes.
 The parameter file I was using to test the shell with a hydro model still crashes out tho.
Is there an error with the way I've set things up?

[py_hydro_shell.pf.txt](https://github.com/agnwinds/python/files/2266900/py_hydro_shell.pf.txt)


nick

**Comment by Higginbottom** [comment]
The model has been fixed - the one remaining issue mentioned in my last post is really one of a conflict between the domains code and the shell code. It is therefore not really part of this issue.
Closing...

**Comment by kslong** [comment]
@Higginbottom   - Sigh,  I am opening this yet again.   There is a generic problem with shell_wind and domains that is not associated with #397   shell_wind does not work as the second domain for any parameter file, including:

[sv_shell.pf.txt](https://github.com/agnwinds/python/files/2267258/sv_shell.pf.txt)

I have fixed a part of the problem in that the coordinates for  shell_wind were hard wired to be associated with wmain cells 0 - 3.  This is because shell_wind goes around a lot of the machinery for setting up a model.  Currently, the program runs through the first ionization cycle, but segfauts when it tries to update the wind for cycle 1.  It looks as it is trying to update an element of plasmamain that does not exist.  

(Do we get credit in James' game for how many times we open and close and issue?)

**Comment by kslong** [comment]
@Higginbottom - I believe I have fixed the problem with shell_wind failing in multiple domains.  The final error was in these lines of wind_update, where you were trying to accumulate information about what happened in the previous cycle.   

![screenshot_820](https://user-images.githubusercontent.com/2530901/43806684-992a5d5e-9a6a-11e8-9acc-97522fe46c50.png)

Note that nstart in zdom refers to the first wind cell for a domain, and does not tell one where the plasma cells are.  You have to get that mapping from the wind cell.

Having said that this run, I need you to see whether you can come up with a test to see if it really works.  Possibly the way to do this, is to compare results to a wind model that has two domains, an sv model with extremely low mass loss rate and then a shell.  The one would compare this to a model with just the shell.  Note that I could do this, but ultimately I don't know what the right answer is.

At any rate, the program does not fall over anymore.

**Comment by kslong** [comment]
@Higginbottom   I am going to close the shell wind issue.  I believe it works correctly now.  It still wold be worthwhile for you to test it further.  Note that the .pf file has changed slightly for shell-wind so you will need to adapt your tests accordingly.

**Comment by Higginbottom** [comment]
Still seems to be a problem.
I've just been running a series of shell wind runs to understand Chris Does SEDs. With a simple brem model like this:

[input.pf.txt](https://github.com/agnwinds/python/files/2904542/input.pf.txt)

Commits up to bf05257fd80f82416f56231dca84f549a5850410 gives T_e=1.071483e+07,
whereas commit 6d750646b9f23720085be46af1560d6ec82e0dfd and onwards gives T_e=7.189013e+04. 

I'm unsure as to the reason why - Knox mentions that the ".pf file has changed slightly for shell-wind" but I'm not sure how, so perhaps I should have changed the .pf file somehow. But everything appears to be identical across the commit. 

Here is a summary line from bf05
OUTPUT Lum_agn= 5.683666e+33 T_e= 1.071483e+07 N_h= 9.984854e+06 N_e= 1.206882e+07 alpha= 0.000000 IP(sim_2010)= 1.100538e+06 Measured_IP(cloudy)= 1.938465e+02 Measured_Xi= 1.000457e+05 distance= 1.000000e+11 volume= 1.256638e+23 mean_ds=1.002253e+00

And the same from 6d75

OUTPUT Lum_agn= 5.683666e+33 T_e= 7.189013e+04 N_h= 9.984854e+06 N_e= 1.206859e+07 alpha= 0.000000 IP(sim_2010)= 1.100538e+06 Measured_IP(cloudy)= 1.938465e+02 Measured_Xi= 1.000457e+05 distance= 1.000000e+11 volume= 1.256638e+23 mean_ds=1.002253e+00


Investigating....

**Comment by Higginbottom** [comment]
Adiabatic cooling is huge after the change. This suggests a problem with how the velocity is calculated.

**Comment by Higginbottom** [comment]
Almost nothing was changed in the commit - it must be to do with the lines in spherical.c

So here is a simple printout of w[0].r to w[3].r from before the commit

BLAH 9.99999999990000000000e+10 1.00000000000000000000e+11 1.00000000001000000000e+11 1.00000000002000000000e+11
and after

9.50000000000000000000e+10 1.00000000000000000000e+11 1.00000000001000000000e+11 1.05000000001050003052e+11

So, before we had a uniform setup of three shells, each 1cm thick. Two ghost, and one real. The velocities in both models are the same...

0 1cm/s 0 0 at the edges of each of the shells - so I think that the div_v calculations will be significantly different - hence the massive adiabatic cooling.

So, the question is - is the change to the calculation of the grid points in shell_make_grid correct?

If so, I can turn off adiabatic cooling - which is what I will do to get better stability plots for my current work.....

So, Knox, the question is - were the changes made to the grid spacing in shell_make_grid necessary to fix the bug or were they made for other reasons?

**Comment by kslong** [comment]
As the discussion of the issue indicates,  they were made to fix the bug.

I am at a meeting today and so I cannot work on this.  If you are correct, Nick, that the problem is the adiabatic heating, and that this is associated with the divergence of the velocity (which is a cell-centered quantity), then my guess is that it has something to do with the ds used in the calculation of the the divergence.  Normally, ds should not end up with a point in a neighboring cell, but if the cell is small enough (and the shell models are smaller have an active cell that is smaller than any other case we look at), then the program may be sampling the velocity in the ghost cell, which is almost guaranteed to give the incorrect answer.   If that is correct, then we should be adjusting the length of ds, to make sure it stays within the cell, because we don't want the calculation to be affected by anything in the ghost cell.

**Comment by kslong** [comment]
OK, I took a quick look at this.  div is calculated in wind2d.c around line 809.  There is an attempt to guess what ds should be, but it does not look very sophisticated to me.  I think this is likely the problem.

**Comment by Higginbottom** [comment]
Ah, jolly good. I’ve been running with adiabatic cooling turned off - which is probably the right thing for the shell model - do you think we need to fix this?

**Comment by kslong** [comment]
We should definitely fix it.  If we don’t it will show up again when you least expect it, and it may be far less obvious what the problem is.  It should be easy to calculate the distance to the corners of a cell, and use a fraction of this in calculating ds.

**Comment by Higginbottom** [comment]
I'm taking a look at it now I've merged my branch back into dev...

**Comment by Higginbottom** [comment]
So the obvious way of doing this is to take the minimum (non-zero) value of 

wmain[icell].x[i]-x_zero[i]

where I goes 0-2 - i=1 is the y axis, which is normally 0 in a 2D model..

testing...

**Comment by Higginbottom** [comment]
something like

delta=fmin(wmain[icell].x[0]-x_zero[0],fmin(wmain[icell].x[1]-x_zero[1],wmain[icell].x[2]-x_zero[2]));

TBH, I think in the thin shell model - the old adiabatic heating was nonsense - the new one was just different nonsense!
More important to look at a real model.

**Comment by kslong** [comment]
I was thinking something more like

frac=1e-3
d1=wmain[icell].xcen[0]-xmain[icell].x[0]
d2=wmain[icell].xcen[3]-xmain[icell].x[3]
delta=frac*min(d1,d2)

so delta defined on a cell by cell basis using only things in wmain.  

This might need to be done on a coordinate system by coordinate system basis.

**Comment by Higginbottom** [comment]
Our code is almost identical - xzero is wmain[icell].xcen - we only differ substantially in the use of a fraction of this value.


I've coded it up and quickly run the CV and AGN models - just to see if the div_v changes. It does.

This makes things tricky - I suspect that the old way of doing it could well give incorrect estimates of div_v - since the test points used to compute the velocity are likely often outside the cells in question. If I'm reading it right.
Which means the new code could be better - but how to decide?

Will try with the use a fraction....

**Comment by Higginbottom** [comment]
Looks like the fraction is needed to get the larger models to work.

**Comment by Higginbottom** [comment]
So, with a 'fraction' of 1e-3 - running the regression tests, there are changes in most of the regression test spectra. 
Changing the fraction to 1e-6 shows differences between the 1e-3 run in the cv_reflect and cv_reflect2 runs.

**Comment by kslong** [comment]
I expected regression test changes, because this clearly affects how photons scatter.  I presume the regression plots look reasonable though.

**Comment by Higginbottom** [comment]
They do!

here is a link to the plots on dropbox…

https://www.dropbox.com/sh/n21a26v6xdh9xdu/AAChninZOu8N4yWL3s7c8bIZa?dl=0

Nick

**Comment by kslong** [comment]
These changes are just those you would expect due to single additional scatter, or one fewer, which then changes all the follow-on random number generation.   Agreed, Nick?

**Comment by Higginbottom** [comment]
I’m sure you are correct - I’ve been tinkering with the scaling factor - but no great insights.
Will pull in…

**Comment by Higginbottom** [comment]
fixed (again) with #483
